---
- name: My test playbooks
  hosts: all
  become: true
  tasks:
    - name: Copy file to remote host
      copy:
        src: /home/ansadmin/index.html
        dest: /home/ansadmin
        mode: 0600
        owner: sangeerthana
