---
- name: This playbook is used to install httpd
  hosts: all
  become: true
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"

  - name: Start httpd service
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: Install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: Start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: Copying index.html
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0666
