---
- name: Install httpd
  hosts: webservers
  become: true
  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: installed

    - name: starting service
      service:
        name: httpd
        state: started
