---
- name: this playbook is to install tomcat
  hosts: all
  become: true
  tasks:
    - name: Install java on RedHat
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Install java on Debian
      apt:
        name: java
        state: installed
      when: ansible_os_family == "Debian"
  
    - name: Download Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.tar.gz  
        dest: /opt

    - name: extract tomcat
      unarchive:
        src: /opt/apache-tomcat-8.5.87.tar.gz
        dest: /opt
        remote_src: yes
    - name: Add executable permissions
      file: 
        path: /opt/apache-tomcat-8.5.87/bin/startup.sh
        mode: 0777

    - name: start tomcat service
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.87/bin      
